frr defaults traditional
hostname pe1
!
interface lo
 ip address 1.1.1.1/32
!
vrf cust
 ip route 10.1.1.0/24 blackhole
exit-vrf
!
interface eth0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 172.30.0.0/24 area 0
!
mpls ldp
 router-id 1.1.1.1
 address-family ipv4
  discovery transport-address 1.1.1.1
  interface eth0
 exit-address-family
!
router bgp 65000
 bgp router-id 1.1.1.1
 neighbor 2.2.2.2 remote-as 65000
 neighbor 2.2.2.2 update-source lo
 address-family ipv4 unicast
  no neighbor 2.2.2.2 activate
 exit-address-family
 address-family ipv4 vpn
  neighbor 2.2.2.2 activate
 exit-address-family
 !
 bmp targets T1
  bmp connect 172.30.0.1 port 5000 min-retry 1000 max-retry 5000
  bmp monitor ipv4 vpn pre-policy
  bmp monitor ipv4 vpn post-policy
  bmp stats interval 10000
 exit
exit
!
router bgp 65000 vrf cust
 bgp router-id 1.1.1.1
 address-family ipv4 unicast
  redistribute static
  label vpn export auto
  rd vpn export 65000:1
  rt vpn both 65000:1
  export vpn
  import vpn
 exit-address-family
exit
!
fpm address 172.30.0.1 port 2620
!
