frr defaults traditional
hostname pe2
!
interface lo
 ip address 2.2.2.2/32
!
vrf cust
 ip route 10.2.2.0/24 blackhole
exit-vrf
!
interface eth0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 172.30.0.0/24 area 0
!
mpls ldp
 router-id 2.2.2.2
 address-family ipv4
  discovery transport-address 2.2.2.2
  interface eth0
 exit-address-family
!
router bgp 65000
 bgp router-id 2.2.2.2
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 update-source lo
 address-family ipv4 unicast
  no neighbor 1.1.1.1 activate
 exit-address-family
 address-family ipv4 vpn
  neighbor 1.1.1.1 activate
 exit-address-family
exit
!
router bgp 65000 vrf cust
 bgp router-id 2.2.2.2
 address-family ipv4 unicast
  redistribute static
  label vpn export auto
  rd vpn export 65000:2
  rt vpn both 65000:1
  export vpn
  import vpn
 exit-address-family
exit
!
